version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: shadmanul/coturn:4.5.0.6
    environment:
      EXTERNAL_IP: 54.89.211.124
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    network_mode: "host"
    restart: "always"

volumes:
  sqlite:
  logs:
